// zh-TW dictionary for the huckly i18n overlay. Keys are exact trimmed English UI strings.
export const ZH_TW = Object.freeze({
  '3D aircraft — flat icons zoomed out, 3D models up close': '3D 航空器 — 遠看平面圖示，近看 3D 模型',
  '3D model coverage': '3D 模型涵蓋範圍',
  'ACQUIRING REGIONAL NEWS': '擷取區域新聞中',
  'ACTIVE EVENTS': '進行中事件',
  'ACTIVE STYLE': '目前風格',
  'Add a cold, snowy whiteout treatment to the scene.': '為場景加上寒冷、雪白的暴雪效果。',
  'Add the full Starlink broadband shell (thousands of extra points)': '加入完整 Starlink 寬頻殼層（額外數千個點）',
  'ADJUST': '調整',
  'ADJUST ON': '調整 開',
  'AHEAD': '前方',
  'AIRCRAFT': '航空器',
  'Aircraft cockpit view': '航空器座艙視角',
  'Aircraft, vessels and nearby intelligence': '航空器、船舶與周邊情資',
  'AIS vessels': 'AIS 船舶',
  'All': '全部',
  'ALL · DRAG THE NEEDLE': '全部 · 拖曳指針',
  'Allocation': '配置',
  'ALTITUDE': '高度',
  'ALTITUDE · FT': '高度 · FT',
  'Anime': '動漫',
  'Apply bright cel-shaded color and illustrated outlines.': '套用明亮的賽璐璐上色與插畫描邊。',
  'Apply high-contrast monochrome film-noir grading.': '套用高對比黑白的黑色電影調色。',
  'ASCENT PATH ·': '升空路徑 ·',
  'Audio connects directly to the broadcaster after you press play. Your IP is visible to that broadcaster.': '按下播放後，音訊會直接連線到該電台，你的 IP 位址會被該電台看見。',
  'AUTO HOP OFF': '自動跳轉 關',
  'AUTO HOP ON': '自動跳轉 開',
  'AVAILABLE INPUTS ONLY · NOT AN ALL-CLEAR': '僅依現有資料 · 不代表安全無虞',
  'AVAILABLE MISSIONS': '可用任務',
  'Available Space Missions': '可用太空任務',
  'Awaiting telemetry...': '等待遙測資料...',
  'BALANCED': '均衡',
  'Begin with a clean globe': '從乾淨的地球開始',
  'Bloom': '光暈',
  'Bloom / Glow': '光暈 / 輝光',
  'browser-side': '瀏覽器端',
  'C TOGGLE': 'C 切換',
  'CALIBRATION': '校正',
  'Camera pose — click a value to type': '攝影機姿態 — 點擊數值可輸入',
  'Cancel replay': '取消重播',
  'CAPTURE SHOT': '擷取鏡頭',
  'CCTV camera': 'CCTV 攝影機',
  'CCTV OFF': 'CCTV 關',
  'CCTV ON': 'CCTV 開',
  'Celestial': '天體',
  'Celestial ring — reveal the full globe': '天體環 — 顯示完整地球',
  'Choose your first view': '選擇你的起始視角',
  'Clean UI': '簡潔介面',
  'Clear selected data layers': '清除已選資料圖層',
  'Clearing selected data layers': '正在清除已選資料圖層',
  'Close compact Radio controls': '關閉精簡電台控制',
  'Close key setup': '關閉金鑰設定',
  'COCKPIT': '座艙',
  'Cockpit briefing carousel': '座艙簡報輪播',
  'Cockpit briefing controls': '座艙簡報控制',
  'Cockpit briefing pages': '座艙簡報頁面',
  'Cockpit compact Radio controls': '座艙精簡電台控制',
  'Cockpit display and Radio controls': '座艙顯示與電台控制',
  'Cockpit display options': '座艙顯示選項',
  'Cockpit Radio volume': '座艙電台音量',
  'Cockpit vision style': '座艙視覺風格',
  'Collapse briefing panel': '收合簡報面板',
  'Collapse cockpit briefing panel': '收合座艙簡報面板',
  'Collapse contact panel': '收合目標面板',
  'Collapse Contact panel': '收合目標面板',
  'Collapse panel': '收合面板',
  'Collapse Radio': '收合電台',
  'Collapse Radio section': '收合電台區塊',
  'Compact Radio controls': '精簡電台控制',
  'Compact Radio volume': '精簡電台音量',
  'configured externally': '外部設定',
  'Configuring viewer...': '正在設定檢視器...',
  'CONNECTING': '連線中',
  'CONTACT': '目標',
  'Contact cockpit summary': '目標座艙摘要',
  'Contact Context actions': '目標情境操作',
  'CONTACT LOST · LAST KNOWN READOUT · NOT AN ALL-CLEAR': '目標遺失 · 最後已知讀數 · 不代表安全無虞',
  'Contact navigation': '目標導覽',
  'CONTACTS': '目標',
  'CONTACTS — nearest planes · vessels · sites': '目標 — 最近的飛機 · 船舶 · 據點',
  'CONTACTS · 250 KM': '目標 · 250 KM',
  'CONTACTS CONTEXT OFF': '目標情境 關',
  'Context mode': '情境模式',
  'CONTEXT ONLY': '僅情境',
  'Copy share link': '複製分享連結',
  'COVERAGE OFF': '涵蓋範圍 關',
  'CURRENT': '目前',
  'Current aircraft heading': '目前航空器航向',
  'Current cockpit vision style: NORMAL. Activate for next style.': '目前座艙視覺風格：NORMAL。啟用以切換下一個風格。',
  'CURRENT DISTANCE FROM EARTH ·': '目前離地距離 ·',
  'Current style: NORMAL — click for next': '目前風格：NORMAL — 點擊切換下一個',
  'Cycle briefing pages automatically every 9 seconds (Signals → News → Local). Pauses while you hover or focus the panel. Live signal data refreshes continuously either way.': '每 9 秒自動輪播簡報頁（訊號 → 新聞 → 在地）。游標停留或聚焦面板時暫停；即時訊號資料無論如何都會持續更新。',
  'CYCLE OFF': '輪播 關',
  'Cycles the nearest contacts of whatever type you select — planes, vessels, installations. Satellites track independently.': '依你選擇的類型輪流切換最近目標 — 飛機、船舶、設施。衛星獨立追蹤。',
  'DEL': '刪除',
  'Density': '密度',
  'Deselect mission': '取消選取任務',
  'DESTINATION': '目的地',
  'DETECT': '偵測',
  'Detection fade distance': '偵測淡出距離',
  'Detection label allocation': '偵測標籤配置',
  'Detection label density': '偵測標籤密度',
  'Detection opacity outside the keyhole': '鎖孔外偵測不透明度',
  'Detection overlay': '偵測疊加層',
  'Detection Overlay (D)': '偵測疊加層 (D)',
  'Detection overlay: off': '偵測疊加層：關',
  'DIRECTORY BAND': '目錄頻段',
  'DIRECTORY: RADIO BROWSER': '目錄：RADIO BROWSER',
  'Disable cockpit weather effects': '停用座艙天氣效果',
  'Don\'t show this again': '不再顯示',
  'Drag the camera in the world: rings rotate, arrows move, handles set range/FOV': '在場景中拖曳攝影機：環可旋轉、箭頭可移動、控點調整距離/視野',
  'DRAG TO TUNE': '拖曳調頻',
  'EARTH WATCH': '地球觀測',
  'East offset from catalog position (m) — click to type': '相對目錄位置的東向偏移 (m) — 點擊可輸入',
  'Elastic': '彈性',
  'Emulate a green phosphor CRT with scanlines and screen curvature.': '模擬帶掃描線與螢幕弧度的綠色磷光 CRT。',
  'ENABLE': '啟用',
  'Enable CCTV to load camera intersections': '啟用 CCTV 以載入攝影機交會點',
  'Enable CCTV to start camera-linked intelligence summaries.': '啟用 CCTV 以開始攝影機連動的情資摘要。',
  'Enable cockpit weather effects': '啟用座艙天氣效果',
  'Enable Radio, then choose a globe marker or use next.': '啟用電台後，選擇地球上的標記或按下一台。',
  'ENVIRONMENTAL': '環境',
  'ERROR': '錯誤',
  'ESC EXIT': 'ESC 離開',
  'ESC to close': '按 ESC 關閉',
  'ESC to dismiss': '按 ESC 略過',
  'Estimated destination direction': '預估目的地方向',
  'Estimated flight plan': '預估飛行計畫',
  'ESTIMATED FLIGHT PLAN': '預估飛行計畫',
  'Estimated session cost': '預估工作階段費用',
  'EXECUTING': '執行中',
  'EXIT CLEAN VIEW': '離開簡潔視圖',
  'EXIT COCKPIT': '離開座艙',
  'Exit cockpit and return to full globe view': '離開座艙並回到完整地球視圖',
  'Exit cockpit view': '離開座艙視角',
  'Expand briefing panel': '展開簡報面板',
  'Expand cockpit briefing panel': '展開座艙簡報面板',
  'Expand Cockpit display options': '展開座艙顯示選項',
  'Expand Cockpit Radio controls': '展開座艙電台控制',
  'Expand contact panel': '展開目標面板',
  'Expand Contact panel': '展開目標面板',
  'Expand panel': '展開面板',
  'Expand Radio': '展開電台',
  'Expand Radio section': '展開電台區塊',
  'Expand Visual Presets': '展開視覺預設',
  'EXPLORE MANUALLY': '自行探索',
  'EXPORT PRESETS': '匯出預設',
  'Fade': '淡出',
  'Feather': '羽化',
  'Filter stations by station tag': '依電台標籤篩選',
  'FINAL POSITION': '最終位置',
  'FIRST PERSON': '第一人稱',
  'Flights': '航班',
  'FLT': '航班',
  // huckly: controls.js keeps upstream's loader text, but the home view is Taipei.
  'Flying to Austin, TX...': '正在飛往台北…',
  'FOCUS': '聚焦',
  'FRAME · LOADING': '畫面 · 載入中',
  'FRAME · UNAVAILABLE': '畫面 · 無法取得',
  'Free key — register, paste, done': '免費金鑰 — 註冊、貼上、完成',
  'FROM': '出發',
  'GET KEY ↗': '取得金鑰 ↗',
  'Global Context navigation': '全域情境導覽',
  'Globe actions': '地球操作',
  'GROUND SPEED': '地速',
  'GROUND SPEED · KTS': '地速 · KTS',
  'GROUND STATION · PROVIDER SETTINGS': '地面站 · 供應商設定',
  'Heading (compass °) — click to type': '航向（羅盤 °）— 點擊可輸入',
  'Hide UI chrome': '隱藏介面框架',
  'Horizontal FOV (°) — click to type': '水平視野 (°) — 點擊可輸入',
  'HUD layout': 'HUD 版面',
  'IMPORT': '匯入',
  'Initializing photorealistic world...': '正在初始化擬真世界...',
  'Initializing systems...': '正在初始化系統...',
  'Intelligence HUD (H)': '情資 HUD (H)',
  'Internet radio companion': '網路電台',
  'It feels like a forbidden cockpit—then you realize the sources are public and the data is real.': '感覺像闖進禁區座艙——然後你發現來源全是公開的，資料也是真的。',
  'Keep location tray open': '保持地點列展開',
  'Keep visual presets open': '保持視覺預設展開',
  'Latest regional news': '最新區域新聞',
  'LAUNCH SITE ·': '發射場 ·',
  'LAUNCH TIME ·': '發射時間 ·',
  'Launches, spacecraft and orbital context': '發射、太空船與軌道情境',
  'Layout': '版面',
  'LEVEL': '水平',
  'LISTENING': '聆聽中',
  'LIVE CONTACTS': '即時目標',
  'Live earthquakes and active fires, from USGS and NASA': '來自 USGS 與 NASA 的即時地震與火點',
  'Live signals': '即時訊號',
  'LIVE SIGNALS': '即時訊號',
  'LIVE TRACK · COURSE ALIGNED': '即時航跡 · 航向對齊',
  'LOAD': '載入',
  'LOADING 30-DAY MISSION INDEX': '載入 30 天任務索引',
  'Loading the Starlink shell…': '正在載入 Starlink 殼層…',
  'LOCAL': '在地',
  'LOCATION': '位置',
  'Location-based information': '位置相關資訊',
  'MANAGE ↗': '管理 ↗',
  'Map source': '地圖來源',
  'MAP SOURCE': '地圖來源',
  'Metered — a billing-enabled account': '計量計費 — 需啟用帳單的帳戶',
  'MIL': '軍用',
  'Military flights': '軍機',
  'Minimal': '極簡',
  'MISSION': '任務',
  'MISSION CONTROL · FIRST LAUNCH': '任務控制 · 首次啟動',
  'Models': '模型',
  'Mount height above ground (m) — click to type': '架設離地高度 (m) — 點擊可輸入',
  'NAME': '名稱',
  'Navigation, voice, and visual preset controls': '導覽、語音與視覺預設控制',
  'Nearby cohort counts': '周邊群組數量',
  'NEAREST': '最近',
  'NEAREST OBSERVED / MAPPED': '最近 觀測 / 圖資',
  'NEW': '新增',
  'NEWS': '新聞',
  'NEXT': '下一個',
  'Next — nearest unvisited contact in the 250 km window': '下一個 — 250 km 範圍內最近的未造訪目標',
  'Next briefing page': '下一頁簡報',
  'Next cockpit vision style': '下一個座艙視覺風格',
  'Next filtered radio station': '下一個篩選電台',
  'Next filtered station': '下一個篩選電台',
  'Next mission': '下一個任務',
  'Next station': '下一台',
  'Next vision style': '下一個視覺風格',
  'NO AVAILABLE EXAMPLE': '無可用實例',
  'NO PLACE LEFT BEHIND': '無處遺漏',
  'No shots yet. Use CAPTURE SHOT to save current look.': '尚無鏡頭。使用「擷取鏡頭」儲存目前畫面。',
  'NO STATION SELECTED': '未選擇電台',
  'Noir': '黑色電影',
  'Normal': '標準',
  'North offset from catalog position (m) — click to type': '相對目錄位置的北向偏移 (m) — 點擊可輸入',
  'OBSERVED / MAPPED PINGS': '觀測 / 圖資 回報',
  'OFF': '關',
  'OFF AIR': '停播',
  'ON': '開',
  'Open compact Radio controls': '開啟精簡電台控制',
  'Open detailed Radio controls': '開啟詳細電台控制',
  'Open-source mapped/observed context. Missing broadcasts, unloaded map areas, or unmapped sites are not evidence of absence.': '開源圖資／觀測情境。缺少廣播、未載入的地圖區域或未標示的據點，不代表不存在。',
  'Opening space missions…': '正在開啟太空任務…',
  'Operator': '操作員',
  'OPTICAL PLANE · 01': '光學平面 · 01',
  'ORBIT ·': '軌道 ·',
  'Outside': '外部',
  'PARAMETERS': '參數',
  'PAUSE': '暫停',
  'Pause nearest radio station': '暫停最近電台',
  'Pause replay': '暫停重播',
  'Pause selected radio station': '暫停所選電台',
  'PAYLOAD': '酬載',
  'Pin location tray': '釘選地點列',
  'Pin visual presets': '釘選視覺預設',
  'Pitch (° up/down) — click to type': '俯仰（° 上/下）— 點擊可輸入',
  'Play': '播放',
  'PLAY': '播放',
  'Play nearest radio station': '播放最近電台',
  'Play selected radio station': '播放所選電台',
  'Play selected station': '播放所選電台',
  'POSITION UNAVAILABLE': '無法取得位置',
  'POWER UP': '啟動',
  'Power up the globe': '啟動地球',
  'POWERED UP': '已啟動',
  'PRECIP': '降水',
  'PREV': '上一個',
  'PREVIOUS': '上一個',
  'Previous — prior visited contact in the 250 km window': '上一個 — 250 km 範圍內前一個已造訪目標',
  'Previous briefing page': '上一頁簡報',
  'Previous cockpit vision style': '上一個座艙視覺風格',
  'Previous filtered radio station': '上一個篩選電台',
  'Previous filtered station': '上一個篩選電台',
  'Previous mission': '上一個任務',
  'Previous station': '上一台',
  'Previous vision style': '上一個視覺風格',
  'PROJECTION OFF': '投影 關',
  'PROJECTION ON': '投影 開',
  'Proximity': '鄰近',
  'Radio off': '電台關閉',
  'Radio playback': '電台播放',
  'RADIO READY': '電台就緒',
  'Radio volume': '電台音量',
  'Range / monitor-plane distance (m) — click to type': '距離 / 監視平面距離 (m) — 點擊可輸入',
  'Ready': '就緒',
  'READY': '就緒',
  'Reclassify as TR-3B': '重新分類為 TR-3B',
  'Reclassify tracked contact as TR-3B': '將追蹤目標重新分類為 TR-3B',
  'REGION UNAVAILABLE': '無法取得區域',
  'REMOVE': '移除',
  'REPLAY ASCENT': '重播升空',
  'REPLAY SPEED': '重播速度',
  'Replay speed multiplier': '重播倍速',
  'Replay the estimated ascent with a following camera': '以跟隨攝影機重播預估升空路徑',
  'RESET': '重設',
  'RESET CAL': '重設校正',
  'Reset camera and return to full globe view': '重設攝影機並回到完整地球視圖',
  'Reset cockpit to full globe view': '座艙重設為完整地球視圖',
  'Reset to full globe view': '重設為完整地球視圖',
  'Resetting cockpit to full globe view': '正在將座艙重設為完整地球視圖',
  'Resetting to full globe view': '正在重設為完整地球視圖',
  'RESOLVING REGION': '解析區域中',
  'Restore real aircraft': '還原真實航空器',
  'Restoring shared view...': '正在還原分享視角...',
  'RESUME': '繼續',
  'Resume nearest radio station': '繼續播放最近電台',
  'Resume replay': '繼續重播',
  'Resume selected radio station': '繼續播放所選電台',
  'Return UI controls': '恢復介面控制',
  'ROUTE DATA UNAVAILABLE': '無航線資料',
  'RUN LOG': '執行紀錄',
  'SATELLITE SPEED ·': '衛星速度 ·',
  'SAVE CAL': '儲存校正',
  'SAVE KEYS': '儲存金鑰',
  'Scanning active events…': '正在掃描進行中事件…',
  'Scene recipe': '場景腳本',
  'SCENE SUMMARY': '場景摘要',
  'Scope': '觀景窗',
  'Scope — the circular viewport mask': '觀景窗 — 圓形視窗遮罩',
  'Scope edge feather as a percentage of the keyhole radius': '觀景窗邊緣羽化（鎖孔半徑百分比）',
  'Search any location': '搜尋任意地點',
  'Search any location...': '搜尋任意地點...',
  'SEARCH NEARBY SITES': '搜尋周邊據點',
  'SELECT A MISSION TO INSPECT': '選擇要檢視的任務',
  'SELECT CONTACTS TO LOAD OBSERVED / MAPPED PROXIMITY': '選擇目標以載入觀測 / 圖資鄰近資訊',
  'SELECT CONTEXT': '選擇情境',
  'Selected Space Mission': '已選太空任務',
  'SELECTED SPACE MISSION': '已選太空任務',
  'Sharpen': '銳化',
  'Sharpening': '銳化強度',
  'SHOW ALL / DESELECT': '全部顯示 / 取消選取',
  'Show all missions': '顯示所有任務',
  'Show Live Signals': '顯示即時訊號',
  'Show Local Info': '顯示在地資訊',
  'Show Regional News': '顯示區域新聞',
  'Show the globe without a visual filter.': '不套用視覺濾鏡顯示地球。',
  'Showing the full Starlink shell — click for the core catalog only': '顯示完整 Starlink 殼層 — 點擊僅顯示核心目錄',
  'SIG': '訊號',
  'Simulate FLIR-style thermal contrast. Turn up Ironbow for color.': '模擬 FLIR 式熱影像對比，調高 Ironbow 可上色。',
  'Simulate night-vision goggles with green intensification and a tube vignette.': '模擬夜視鏡的綠色增強與鏡筒暗角。',
  'SITE': '據點',
  'SKY': '天空',
  'SNAPS TO AVAILABLE STATIONS': '自動對齊可用電台',
  'Snow': '雪景',
  'SOURCE · UNKNOWN': '來源 · 未知',
  'SOURCE-BACKED EVENTS · NO SYNTHETIC NEWS': '有來源佐證的事件 · 無合成新聞',
  'SPACE MISSIONS': '太空任務',
  'SPACE MISSIONS — launches & orbital assets': '太空任務 — 發射與軌道資產',
  'SPARSE': '稀疏',
  'STAGE': '推進節',
  'STAGE / RE-ENTRY / RECOVERY': '推進節 / 重返 / 回收',
  'START': '開始',
  'Starting live contacts…': '正在啟動即時目標…',
  'STATION SITE': '電台網站',
  'STATION TAG': '電台標籤',
  'STATION UNAVAILABLE': '電台無法使用',
  'STATUS': '狀態',
  'STATUS ·': '狀態 ·',
  'STOP': '停止',
  'Stop radio playback': '停止電台播放',
  'Style': '風格',
  'SUMMARY': '摘要',
  'Supplied by your environment, Keychain, or launcher — change it where it was set': '由環境變數、鑰匙圈或啟動器提供 — 請在原設定處修改',
  'Tactical': '戰術',
  'TEMP': '溫度',
  'The globe already flies keyless. Every key below switches on another real feed — paste one and it\'s saved into this app\'s local configuration, then the server restarts itself. Server-side keys stay on this machine; Google Maps and Cesium ion run in the browser and must be provider-restricted. Keys you configured elsewhere are shown but never touched.': '地球不需金鑰即可運作。下方每把金鑰都會開啟另一個真實資料源——貼上後會存入本應用的本機設定，伺服器接著自動重啟。伺服器端金鑰只留在這台機器；Google Maps 與 Cesium ion 在瀏覽器端執行，必須在供應商端設限。在其他地方設定的金鑰會顯示，但絕不會被更動。',
  'The Google Maps key buys the photorealistic planet — everything else stacks on top.': 'Google Maps 金鑰解鎖擬真星球 — 其他功能都疊加在它之上。',
  'This browser is blocking storage, so that could not be saved.': '此瀏覽器封鎖了儲存空間，因此無法儲存。',
  'This key runs in the browser by design — restrict it at the provider (see SECURITY.md)': '此金鑰依設計在瀏覽器端執行 — 請在供應商端設限（見 SECURITY.md）',
  'Tip: the GEV MIC button in the dock lets you talk to the map.': '提示：Dock 中的 GEV MIC 按鈕可讓你對地圖說話。',
  'TO': '抵達',
  'Tune available internet radio stations': '調到可用的網路電台',
  'Turn off all selected data layers': '關閉所有已選資料圖層',
  'TYPE': '類型',
  'Unavailable': '無法取得',
  'UNKNOWN': '未知',
  'UPDATE SHOT': '更新鏡頭',
  'VIEW': '視角',
  'View switcher': '視角切換',
  'Visible map targets': '可見地圖目標',
  'VISOR LOCK · ACTIVE': '面罩鎖定 · 啟用',
  'Voice control — hold Space to speak; click to toggle voice': '語音控制 — 按住空白鍵說話；點擊切換語音',
  'Voice model tier — applies next session': '語音模型等級 — 下次工作階段生效',
  'VOLUME': '音量',
  'Weather data by Open-Meteo.com': '天氣資料來源：Open-Meteo.com',
  'Weighted': '加權',
  'WIND': '風',
  'Working…': '處理中…',
  'World-overlay fade distance outside the keyhole as a percentage of its radius': '鎖孔外世界疊加層淡出距離（半徑百分比）',
  'World-overlay label and card opacity beyond the fade distance': '淡出距離外的世界疊加層標籤與卡片不透明度',
  'WX': '天氣',

  // --- huckly additions (added after smoke test) ---
  // Home view loader line set in src/main.js.
  'Flying to Taipei, Taiwan...': '正在飛往台北…',
  // Voice panel (src/voice/gevRealtime.js); no code compares these strings.
  'AI AGENT': 'AI 助理',
  'VOICE STANDBY': '語音待命',
  'VOICE ACTIVE': '語音啟用中',
  'VOICE CONTROL': '語音控制',
  'Hold Space to speak · click mic to toggle voice': '按住空白鍵說話 · 點麥克風切換語音',
  'VOICE SYSTEM ERROR': '語音系統錯誤',
  'DISMISS': '關閉',
  'Check microphone permission and network access, then try again.': '請檢查麥克風權限與網路連線後再試一次。',
  // Location search feedback (locationStatus.js default label, ui.js toasts); display-only.
  'Searched location': '搜尋結果',
  'Location not found': '找不到這個地點',
  'Search failed': '搜尋失敗',
  // Panel titles: ui.js only reads them to build "Expand <title>" tooltips.
  'DATA LAYERS': '資料圖層',
  'VISUAL PRESETS': '視覺預設',
  'SCENES': '場景',
  'CONTEXT': '情境',
  'RADIO': '電台',
  'DISPLAY': '顯示',
});
// Strings intentionally left in English because code reads them (see report).
export const EXCLUDED = Object.freeze([
  'LOADING LIVE DATA',
  'REFRESHING LIVE DATA',
  'TURNING OFF LIVE DATA',
  'LIVE DATA OFF',
  'LOAD COMPLETE',
  'LOAD CANCELLED',
  'LOAD FAILED',
  'FETCHING MAPPED SITES',
  'RETRYING MAPPED SITES',
  'loading frames',
  'camera grid ready',
  'syncing road network',
  'DENSE',
  'DENSE ···',
  'DENSE ✕',
  'NORMAL',
  'CCTV',
  'Live AIS Vessels',
  'Bikeshare',
  'Earthquakes (24h)',
  'Live Flights',
  'Datacenters',
  'Dams',
  'FIRMS Active Fires',
  'Global Context',
  'Military Flights',
  'Mapped Installations',
  'Radio',
  'Space Missions (30d)',
  'Satellites',
  'Submarine Cables',
  'Street Traffic',
]);
